language: node_js
node_js:
  - "node"
before_install:
  - npm install -g yarn
branches:
  only:
    - main
notifications:
  email:
    recipients:
      - noah.song@z-emotion.com
// package.json
{
  "name": "next-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "test": "exit"  // add this line
  },
  "dependencies": {
    "next": "9.3.0",
    "react": "16.13.0",
    "react-dom": "16.13.0"
  }
}
